try {
  // Code that may throw an error
  let result = someFunctionThatMightFail();
  console.log(result);
} catch (error) {
  // Code to run if an error occurs
  console.error(error.message);
}
